# Generated by Django 2.0.2 on 2018-02-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='BlogsPost',
        ),
    ]
